/* EQUIPMENT: every weapon, armour piece and other item the tool knows about.
   Each group has a key (melee, ranged, armour, misc), a title, and a list of items.
   Item fields:
     n  name (warbands and units refer to items by this exact name)
     c  price in gold crowns
     d  short flavour description shown in the tool
   Optional item fields (armour):
     max       most that one warrior can carry (shows a counter instead of a tick box)
     sv        armour save this item gives (5 means 5+)
     svMin     best save that this item can give on its own (used by shields and similar)
     svBonus   extra armour save added on top of other armour
     fx        stat changes, for example {"M":-1}
     cap       raises the racial maximum of a stat, for example {"S":1}
   Optional item fields (weapons, melee and ranged):
     str       Strength used for to-wound rolls: "" means as the user's own Strength,
               "+1"/"+2"/"-1" means a modifier on the user's Strength, or a plain number
               ("3", "4"...) for missile weapons with a fixed Strength. Reference only;
               the tool does not use this for the model's own Strength stat.
     rng       range in inches for a ranged weapon (omitted for melee weapons)
     ap        the armour save penalty this weapon inflicts on the target, e.g. -1
               (an axe) or -2 (blackpowder weapons). Omit for weapons with no penalty.
     noSave    true if the weapon allows no armour save at all (ignore ap if set)
     wd        the weapon's own special rule(s) (parry, two-handed, strikes last,
               and so on). Where it has more than one named rule, write it as
               "Name: text. Name2: text2." (a capitalised phrase, a colon, then its
               text) and the tool shows each one on its own line, named in bold,
               instead of one run-on paragraph. A weapon with a single unnamed rule
               (e.g. "Parries.") is left as plain text
   These weapon fields are reference only, sourced from mordheimer.net's Close-combat,
   Missile and Blackpowder weapon pages; check them against your rulebook. They are not
   used in any cost or stat calculation, since Mordheim doesn't resolve combat here.
   A warband or unit lists what it may buy in gear:[...] using item names or group keys.
   A warband or unit can also override a price with costs:{"Bow":15}. */
const EQUIPMENT = {
  "melee": {"n":"Melee weapons","list":[
    {"n":"Sword","c":10,"d":"","str":"","wd":"Parries.","max":2},
    {"n":"Axe","c":5,"d":"","str":"","ap":-1,"wd":"Cutting Edge.","max":2},
    {"n":"Mace","c":3,"d":"","str":"","wd":"Concussion (2-4 is Stunned).","max":2},
    {"n":"Hammer","c":3,"d":"","str":"","wd":"Concussion (2-4 is Stunned).","max":2},
    {"n":"Spear","c":10,"d":"","str":"","wd":"Strike First: when charged. Unwieldy: only a shield/buckler in the other hand, no second weapon."},
    {"n":"Halberd","c":10,"d":"","str":"+1","wd":"Two-handed."},
    {"n":"Double-handed weapon","c":15,"d":"","str":"+2","wd":"Two-handed. Strike Last: always strikes last."},
    {"n":"Flail","c":15,"d":"","str":"+2","wd":"Heavy: the +2 Strength applies only in the first round of each combat. Two-handed."},
    {"n":"Spiked Gauntlet","c":15,"d":"","str":"","wd":"Counts as an extra hand weapon and a buckler; parries. Heroes may not use it."},
    {"n":"Dwarf Axe","c":15,"d":"Dwarf Troll Slayer only","str":"","ap":-1,"wd":"Cutting Edge. Parry: a second Dwarf Axe (or a Dwarf Axe and a sword) doesn't parry twice, but lets you re-roll a failed parry.","max":2},
    {"n":"Trident","c":15,"d":"","str":"","wd":"Parries; strikes first when charged."},
    {"n":"Morning star","c":15,"d":"","str":"+1","wd":"Heavy: the +1 Strength applies only in the first round of each combat. Difficult to use: no second weapon or buckler (a shield is fine)."},
    {"n":"Club","c":3,"d":"","str":"","wd":"Concussion (2-4 is Stunned).","max":2},
    {"n":"Sigmarite warhammer","c":15,"d":"","str":"+1","wd":"Concussion: 2-4 is Stunned. Holy Weapon: +1 to wound Possessed and Undead (still needs a natural 6 for a critical). Matriarchs and Sister Superiors only may carry two.","max":2},
    {"n":"Steel whip","c":10,"d":"","str":"","wd":"Cannot be parried. Whipcrack: +1 Attack when charging or being charged.","max":2},
    {"n":"Weeping Blades","c":50,"d":"Bought as a pair.","str":"","wd":"Pair: used in pairs for +1 Attack. Venomous: permanently coated in Black Lotus (a 6 to hit always wounds). Parry."},
    {"n":"Fighting Claws","c":35,"d":"Bought as a pair.","str":"","wd":"Pair: used in pairs for +1 Attack. Climb: +1 Initiative for climbing tests. Parry: re-rolls one failed attempt, like a sword and buckler. Cumbersome: no other weapons may be carried."},
    {"n":"Battle Axe","c":5,"d":"","str":"","ap":-1,"wd":"Cutting Edge, as an axe.","max":2},
    {"n":"Warp-Glaive","c":45,"d":"Engineer only (Clan Skryre).","str":"+2","wd":"Two-handed; a shield may not be carried, but a shield already worn still gives +1 to armour saves against shooting. Unstable: a natural 1 to wound hits the wielder with a Strength 3 hit that ignores armour saves and burns out the coils, so it fights as a plain Halberd (Strength +1) for the rest of the battle."},
    {"n":"Ball & Chain","c":15,"d":"","str":"+2","noSave":true,"wd":"Incredible Force: no armour save; a successful wound does 1D3 wounds instead of 1. Random: moves 2D6 inches in a random direction each of its turns instead of moving normally, and counts as charging anything it hits; enemies are -1 to hit it. Cumbersome: no other weapons or gear; usable only with Mad Cap Mushrooms. Unwieldy: roll for Injury for the wielder after the battle as if taken out of action, even if he wasn't."},
    {"n":"Gromril Mace","c":9,"d":"Three times the normal price (starting warband price).","str":"","ap":-1,"wd":"Gromril: an extra -1 armour save modifier; concussion (2-4 is stunned).","max":2},
    {"n":"Gromril Hammer","c":9,"d":"Three times the normal price.","str":"","ap":-1,"wd":"Gromril: an extra -1 armour save modifier; concussion (2-4 is stunned).","max":2},
    {"n":"Gromril Axe","c":15,"d":"Three times the normal price.","str":"","ap":-2,"wd":"Gromril: an extra -1 armour save modifier; cutting edge.","max":2},
    {"n":"Gromril Sword","c":30,"d":"Three times the normal price.","str":"","ap":-1,"wd":"Gromril: an extra -1 armour save modifier; parries.","max":2},
    {"n":"Gromril Dwarf Axe","c":45,"d":"Three times the normal price.","str":"","ap":-2,"wd":"Gromril: an extra -1 armour save modifier; cutting edge; parries. a second dwarf axe (or a dwarf axe and a sword) doesn't parry twice, but lets you re-roll a failed parry.","max":2},
    {"n":"Gromril Double-handed weapon","c":45,"d":"Three times the normal price.","str":"+2","ap":-1,"wd":"Gromril: an extra -1 armour save modifier; two-handed; always strikes last."},
    {"n":"Gromril Spear","c":30,"d":"Three times the normal price.","str":"","ap":-1,"wd":"Gromril: an extra -1 armour save modifier; strikes first when charged. only a shield/buckler in the other hand, no second weapon."},
    {"n":"Gromril Halberd","c":30,"d":"Three times the normal price.","str":"+1","ap":-1,"wd":"Gromril: an extra -1 armour save modifier; two-handed."},
    {"n":"Starblade","c":15,"d":"","str":"","wd":"+1 to the enemy's armour save. Parries the first successful hit of any combat on a 4+.","ap":1,"max":2},
    {"n":"Starsword","c":30,"d":"","str":"+1","noSave":true,"wd":"Parry. Ignores Armour: ignores all armour saves except ward and dodge saves.","max":2},
    {"n":"Choppa","c":10,"d":"Counts as a Morning star.","str":"+1","wd":"Counts as a Morning star.","max":2},
    {"n":"Lance","c":20,"d":"","str":"+2 charging on horseback","wd":"Cavalry weapon: usable only while mounted on a warhorse. Cavalry Bonus: +2 Strength when charging, that turn only."},
    {"n":"Beastlash","c":10,"d":"Beastmaster only.","str":"-1","wd":"Beastbane: causes fear in animals, which must pass a Fear test to charge or be charged by it. Cannot be parried. Whipcrack: +1 Attack when charging or being charged.","max":2},
    {"n":"Dark Elf Blade (upgrade)","c":20,"d":"Weapon upgrade for a sword or dagger.","str":"","wd":"Upgrades a sword or dagger, keeping its own rules. Critical Damage: +1 on the critical hit chart. Wicked Edge: a roll of 2-4 on the injury chart is Stunned."},
    {"n":"Katar","c":5,"d":"","str":"","ap":-1,"max":2},
    {"n":"Boss Pole","c":20,"d":"Acts as a spear; models within 6 inches ignore animosity.","str":"","wd":"Strike First: when charged, in the first round. Unwieldy: only a shield/buckler in the other hand, no second weapon. Ignore Animosity: heroes and Goblin henchmen within 6 inches ignore it."},
    {"n":"Rapier","c":15,"d":"","str":"","ap":1,"wd":"Parry. Barrage: a hit that fails to wound may attack again at a cumulative -1 to hit (down to needing a 6), as long as it keeps hitting. Armour Save: enemy armour saves against it are at +1.","max":2},
    {"n":"Main Gauche","c":7,"d":"","str":"","ap":1,"wd":"Parries.","max":2},
    {"n":"Pike","c":12,"d":"","str":"","wd":"Strike First: +1 Initiative in the first round. Two-handed; a shield still gives +1 to armour saves against shooting."},
    {"n":"Stone Axe","c":3,"d":"Counts as a club.","str":"","wd":"Counts as a club.","max":2},
    {"n":"Boat Hook","c":8,"d":"","str":"-1","wd":"Strike First: in the first round of any close combat, whoever charged. Two-handed."},
    {"n":"Cat O' Nine Tails","c":8,"d":"Heroes only.","str":"","ap":1,"wd":"Cannot be parried. Weak: +1 to the enemy's armour save (6+ if none). Whipcrack: +1 Attack when charging or being charged.","max":2},
    {"n":"Staff","c":3,"d":"","str":"","wd":"Counts as a club.","max":2},
    {"n":"Disease Dagger","c":15,"d":"","str":"","ap":1,"wd":"+1 Enemy Armour Save: +1 to the enemy's armour save (6+ if none). Infecting: a natural 6 to hit also forces a Toughness test (roll a D6; higher than Toughness means an extra wound); Undead and Possessed are immune. A second Disease Dagger gives +1 Attack, no further effect.","max":2},
    {"n":"Censer","c":40,"d":"Rare 9, Skaven only.","str":"+2","wd":"Two-handed: cannot use a shield, buckler or second weapon. Heavy: the +2 Strength applies only in the first round. Fog of Death: anyone hit, and the wielder himself, tests Toughness (roll a D6; higher than Toughness, or any 6, means an extra wound with no save); Undead and Possessed are immune; with Fog-enhancing warpstone shards, the wielder is also -1 to hit with missile weapons."},
    {"n":"Serpent Staff","c":30,"d":"Liche Priests only.","str":"","wd":"Two-handed; parries. Instead of his own attacks and parries, may make one attack at WS4 S4 that always strikes first."},
    {"n":"Kitchen Knife","c":2,"d":"","str":"","ap":1,"wd":"+1 to the enemy's armour save (6+ if none).","max":2},
    {"n":"Cleaver","c":3,"d":"","str":"","ap":-1,"max":2},
    {"n":"Ladle","c":2,"d":"","str":"","noSave":true,"wd":"Only a shield's save applies (or a skill save); a natural 6 to hit disarms the enemy.","max":2},
    {"n":"Tenderiser","c":3,"d":"","str":"","wd":"Concussion (2-4 is Stunned).","max":2},
    {"n":"Claw of the Old Ones","c":30,"d":"","str":"+1","noSave":true,"wd":"No armour save allowed. Parries.","max":2},
    {"n":"Dragon Sword","c":20,"d":"","str":"+1","wd":"Two-handed; +1 armour save vs shooting with a shield. Parry. Also called Katana in older material."},
    {"n":"Cathayan longsword","c":75,"d":"Emissary and Officer only.","str":"","wd":"Parries. Mastercrafted: +1 Initiative and +1 Weapon Skill.","max":2},
    {"n":"Quarter staff","c":15,"d":"","str":"","wd":"+1 Initiative; parries; cannot combine with another weapon or shield (may combine with unarmed Monk attacks).","max":2},
    {"n":"Chain sticks","c":20,"d":"","str":"","wd":"Flurry: +2 Attacks in the first round of each close combat; otherwise counts as two hand weapons. Two-handed."},
    {"n":"Man-catcher","c":25,"d":"Gaolers only.","str":"","wd":"Capture: an out-of-action result becomes a capture instead (no Serious Injury roll) unless the target is a large creature or an animal. Two-handed."},
    {"n":"Broadsword","c":15,"d":"","str":"+1","wd":"No second weapon or buckler (a shield is fine); always strikes last unless Strongman."},
    {"n":"Shortsword","c":7,"d":"","str":"","ap":1,"wd":"Parries; +1 to the enemy's armour save (6+ if none).","max":2},
    {"n":"Hedonist Whip","c":15,"d":"Heroes only.","str":"","wd":"Cannot be parried.","max":2},
    {"n":"Slaaneshi Man-Catcher","c":30,"d":"Whipmaster only.","str":"","wd":"Two-handed; an out-of-action result becomes a capture."},
    {"n":"Misericordia","c":5,"d":"Ignores armour saves against knocked-down enemies.","str":"","ap":1,"wd":"+1 to the enemy's armour save (6+ if none). Against a knocked-down enemy, roll two dice to wound and keep the higher.","max":2},
    {"n":"Boar Spear","c":30,"d":"Aristocrat only.","str":"","wd":"Strikes first when charged."},
    {"n":"Ogre club","c":10,"d":"Stuns on 2-4; -1 to armour saves when used two-handed.","str":"","ap":-1,"wd":"Concussion: 2-4 is Stunned. Crushing Attack: used two-handed, the defender treats it as one Strength higher for parrying."},
    {"n":"Iron fist","c":15,"d":"Parries like a buckler.","str":"","wd":"Parry. Gloved: no other weapon in that hand (so no double-handed weapon). Dual-role: a second Iron Fist, or an Iron Fist and a sword, lets you re-roll a failed parry.","max":2},
    {"n":"Beastwhip","c":25,"d":"Clan Moulder only; cannot be parried.","str":"-1","wd":"Cannot be parried.","max":2},
    {"n":"Thingcatcher","c":20,"d":"Clan Moulder only; two-handed, Strength +1.","str":"+1","wd":"Two-handed."},
    {"n":"Wizard's Staff","c":10,"d":"Two-handed; parries; stuns on 2-4.","str":"","wd":"Two-handed; parries; stuns on 2-4."},
    {"n":"Chest Talon","c":15,"d":"Strigany only; two-handed, Strength +1, +1 to wound Vampires.","str":"+1","wd":"Two-handed; +1 to wound Vampires."},
    {"n":"Silver-tip Stake","c":15,"d":"+1 to injury rolls against Vampires.","str":"","wd":"+1 to injury rolls against Vampires.","max":2},
    {"n":"Katana","c":20,"d":"","str":"+1","wd":"Two-handed; parries; the older name for a Dragon Sword."},
    {"n":"Kanabo","c":15,"d":"Strength +1; stuns on 2-4.","str":"+1","wd":"Concussion (2-4 is Stunned).","max":2},
    {"n":"Kusarigama","c":20,"d":"Two-handed; cannot be parried.","str":"","wd":"Two-handed; cannot be parried."},
    {"n":"Sai","c":30,"d":"Sword breaker.","str":"","wd":"Parries; on a successful parry, may break the enemy's weapon on a 4+.","max":2},
    {"n":"Barbed Whip","c":15,"d":"Cannot be parried; whipcrack.","str":"","wd":"Cannot be parried. Whipcrack: +1 Attack when charging or being charged (only one +1, even if charged by several). Enrage: while not himself in combat, Warhounds of Chaos within 4 inches get +1 Attack.","max":2},
    {"n":"Great Axe","c":25,"d":"Chosen of Chaos only. Strength +2, strikes last, extra -1 save.","str":"+2","ap":-1,"wd":"Two-handed. Strike Last: always strikes last unless Strongman. Cutting Edge."},
    {"n":"Poison Daggers","c":25,"d":"A pair; extra attack and Black Lotus poison.","str":"","ap":1,"wd":"Paired: used in pairs for +1 Attack. Poisoned: permanently coated in Black Lotus (a 6 to hit always wounds). +1 Enemy Armour Save: +1 to the enemy's armour save (6+ if none)."},
    {"n":"Obsidian weapon","c":30,"d":"Chaos Dwarfs only; 60 gc in its own entry on the site.","str":"+1","wd":"Blemished: may not be used by Dwarfs, Elves, Sisters of Sigmar, Witch Hunters or Priests. Heavy: always strikes last.","max":2},
    {"n":"Hobgoblin Poisoned Daggers","c":15,"d":"Hobgoblins only; a pair coated in Black Lotus.","str":"","ap":1,"wd":"Pair: used in pairs for +1 Attack. Swift: +1 Initiative. Poisoned: permanently coated in Black Lotus (a 6 to hit always wounds). +1 Enemy Armour Save: +1 to the enemy's armour save (6+ if none)."},
    {"n":"Draich","c":25,"d":"A two-handed elven sword that does not strike last.","str":"","wd":"Two-handed; parries."},
    {"n":"Whirling Blades","c":30,"d":"A pair of chained axes; Doomseekers only.","str":"","wd":"A pair of chained axes."},
    {"n":"Scythe","c":0,"d":"Priests of Morr only; cost not listed on the site.","str":"","max":2},
    {"n":"Pry Bar","c":10,"d":"Acts as a club and can parry.","str":"","wd":"Counts as a club; parries.","max":2},
    {"n":"Chainsaw Sword","c":15,"d":"Causes fear; -2 to armour saves.","str":"","ap":-2,"wd":"Causes fear.","max":2},
    {"n":"Electric Trident","c":15,"d":"Stuns on 2-4.","str":"","wd":"Stuns on 2-4.","max":2},
    {"n":"Dagger","c":2,"d":"The first is free.","str":"","ap":1,"wd":"+1 to the enemy's armour save (6+ if none).","max":2}
  ]},
  "ranged": {"n":"Missile weapons","list":[
    {"n":"Bow","c":10,"d":"","str":"3","rng":24},
    {"n":"Crossbow","c":25,"d":"","str":"4","rng":30,"wd":"May not move and fire (may still pivot on the spot or stand up)."},
    {"n":"Pistol","c":15,"max":2,"d":"","str":"4","rng":6,"ap":-2,"wd":"Prepare Shot: fires every other turn (every turn with a brace). Save Modifier: the -2 armour save penalty. Hand-to-Hand: usable alongside another weapon for +1 Attack at Strength 4 with the -2 save modifier, once per combat (2 Attacks with a brace, in the first round only).","rules":["misfire"]},
    {"n":"Handgun","c":35,"d":"","str":"4","rng":24,"ap":-2,"wd":"Prepare Shot: fires every other turn. Move or Fire: may not move and fire. Save Modifier: the -2 armour save penalty.","rules":["misfire"]},
    {"n":"Javelins","c":5,"d":"","str":"","rng":8,"wd":"Thrown weapon: no range or move penalty."},
    {"n":"Duelling pistol","c":30,"max":2,"d":"","str":"4","rng":10,"ap":-2,"wd":"Accuracy: +1 to hit. Prepare Shot: fires every other turn (every turn with a brace). Save Modifier: the -2 armour save penalty. Hand-to-Hand: usable alongside another weapon for +1 Attack at Strength 4 with the -2 save modifier, once per combat (2 Attacks with a brace, in the first round only).","rules":["misfire"]},
    {"n":"Long bow","c":15,"d":"","str":"3","rng":30},
    {"n":"Blunderbuss","c":30,"d":"","str":"3","rng":16,"wd":"Shot: a 16 inch line; every model in its path takes a Strength 3 hit. Fire Once: fires only once per battle (too slow to reload).","rules":["misfire"]},
    {"n":"Hunting Rifle","c":200,"d":"","str":"4","rng":48,"ap":-2,"wd":"Prepare Shot: fires every other turn. Move or Fire: may not move and fire. Pick Target: may target any visible enemy, not just the closest. Save Modifier: the -2 armour save penalty.","rules":["misfire"]},
    {"n":"Sling","c":2,"d":"","str":"3","rng":18,"wd":"May fire twice if it didn't move that turn, but only within half range (9 inches); each shot at -1 to hit if it does."},
    {"n":"Short Bow","c":5,"d":"","str":"3","rng":16},
    {"n":"Throwing stars","c":15,"d":"","str":"","rng":6,"wd":"Thrown weapon: no range or move penalty; cannot be used in close combat."},
    {"n":"Blowpipe","c":25,"d":"","str":"1","rng":8,"wd":"Poison: a 6 to hit always wounds; cannot cause critical hits. Stealthy: may fire while hidden; the target gets an Initiative test to spot the shooter.","ap":1},
    {"n":"Warplock pistol","c":35,"max":2,"d":"","str":"5","rng":8,"ap":-3,"wd":"Prepare Shot: fires every other turn (every turn with a brace). Save Modifier: the -3 armour save penalty. Hand-to-Hand: usable alongside another weapon for +1 Attack at Strength 5 with the -3 save modifier, once per combat (2 Attacks with a brace, in the first round only).","rules":["misfire"]},
    {"n":"Crossbow pistol","c":35,"d":"","str":"4","rng":10,"wd":"Shoot in Hand-to-Hand: may fire once in the first round of hand-to-hand combat, resolved before blows are struck, at an extra -2 to hit. Hand-to-Hand: also usable as a melee pistol."},
    {"n":"Throwing knives","c":15,"d":"","str":"","rng":6,"wd":"Thrown weapon: no range or move penalty; cannot be used in close combat."},
    {"n":"Double-barrelled pistol","c":30,"max":2,"d":"","str":"4","rng":6,"ap":-2,"wd":"Prepare Shot: fires every other turn (every turn with a brace). Save Modifier: the -2 armour save penalty. Double-barrelled: firing both barrels needs one to-hit roll, but wound each shot separately; place 2 reload tokens (4 for a brace) and clear one each turn before firing again. Hand-to-Hand: also usable in melee (as a Pistol).","rules":["misfire"]},
    {"n":"Double-barrelled hunting rifle","c":300,"d":"","str":"4","rng":48,"ap":-2,"wd":"Double-barrelled: every hit lands two Strength 4 hits instead of one. Reload: each barrel takes a full turn to reload; a lone barrel fires like a normal rifle in the meantime.","rules":["misfire"]},
    {"n":"Sunstaff","c":35,"d":"","str":"4","rng":24,"noSave":true,"wd":"Accurate: no penalty for long range. No Save: no armour save allowed."},
    {"n":"Bolas","c":5,"d":"","str":"special","rng":16,"wd":"One use, recovered after the battle. Dangerous: a natural 1 to hit hits the wielder at Strength 3 instead. Entangle: the target can't move (and is -2 WS in combat, though it may still shoot) until it rolls a 4+ in a Recovery phase."},
    {"n":"Tufenk","c":15,"d":"","str":"2","rng":8,"wd":"Prepare Shot: fires every other turn. Fire: a hit that scores 4+ on a D6 sets the target on fire (2+ against Mummies, at Strength 3)."},
    {"n":"Repeater Crossbow","c":35,"d":"","str":"3","rng":24,"wd":"May fire twice per turn, both shots at an extra -1 to hit."},
    {"n":"Throwing Weapons","c":15,"d":"","str":"","rng":8,"wd":"Thrown weapon: no range or move penalty."},
    {"n":"Throwing Axe","c":15,"d":"","str":"","rng":6,"wd":"Thrown weapon: no range or move penalty."},
    {"n":"Belaying Pin","c":3,"d":"","str":"-1","rng":6,"ap":1,"wd":"Awkward Thrown Weapon: no range penalty, but -1 to hit if used after moving. Weak: +1 to the enemy's armour save (6+ if none)."},
    {"n":"Swivel Gun","c":65,"d":"One per warband.","str":"","wd":"Cumbersome: -1 Movement and -1 Initiative all battle; never fired twice in a turn or after moving. Prepare Shot: may not move and fire; fires every other turn. Maximum 1 per warband. Always uses the optional Blackpowder rules. Special Ammunition: fires its own ammunition (see Ball/Chain/Grape Shot)."},
    {"n":"Elf Bow","c":35,"d":"","str":"3","rng":36,"ap":-1},
    {"n":"Nehekharan Javelin","c":10,"d":"Tomb Lords only.","str":"","rng":8,"wd":"Thrown weapon: no range or move penalty; +1 to hit."},
    {"n":"Hochland Long Rifle","c":200,"d":"","str":"4","rng":48,"ap":-2,"wd":"Prepare Shot: fires every other turn. Move or Fire: may not move and fire. Pick Target: may target any visible enemy, not just the closest. Save Modifier: the -2 armour save penalty.","rules":["misfire"]},
    {"n":"Sun Gauntlet","c":40,"d":"","str":"4","rng":12,"noSave":true,"wd":"Accurate: no penalty for long range. No Save: no armour save allowed. Hand-To-Hand: usable in hand-to-hand combat each round at Strength 4 with no armour save, alongside another close combat weapon."},
    {"n":"Double-barrelled duelling pistol","c":35,"max":2,"d":"","str":"4","rng":9,"ap":-2,"wd":"Accuracy: +1 to hit. Prepare Shot: fires every other turn (every turn with a brace). Save Modifier: the -2 armour save penalty. Double-barrelled: firing both barrels needs one to-hit roll, but wound each shot separately; place 2 reload tokens (4 for a brace) and clear one each turn before firing again. Hand-to-Hand: also usable in melee (as a Duelling pistol).","rules":["misfire"]},
    {"n":"Double-barrelled handgun","c":45,"d":"","str":"4","rng":24,"ap":-2,"wd":"Prepare Shot: fires every other turn. Move or Fire: may not move and fire. Save Modifier: the -2 armour save penalty. Double-barrelled: firing both barrels needs one to-hit roll, but wound each shot separately; place 2 reload tokens and clear one each turn before firing again.","rules":["misfire"]},
    {"n":"Hand-held Mortar","c":70,"d":"","str":"4","rng":24,"ap":-2,"wd":"Prepare Shot: fires every other turn. Move or Fire: may not move and fire. Save Modifier: the -2 armour save penalty. Scatter: a miss lands 2D6 inches away in a random direction. Explosive: the target and anything within 1.5 inches each take a Strength 4 hit. Always uses the optional Blackpowder rules.","rules":["misfire"]},
    {"n":"Chaos Dwarf Blunderbuss","c":40,"d":"Chaos Dwarfs only; a 16 inch line of Strength 3 hits.","str":"3","rng":16,"wd":"Shot: a 16 inch line; every model in its path takes a Strength 3 hit. Prepare Shot: reloadable, fires every other turn instead of only once.","rules":["misfire"]},
    {"n":"Pigeon Bombs","c":25,"d":"","str":"4","wd":"Move or Fire: may not move and fire. Temperamental: hits on a D6 of 5-6 rather than Ballistic Skill (2-4 the pigeon explodes harmlessly, a 1 it explodes in the thrower's hands, hitting him and everyone within 1.5 inches at Strength 4). Explosive Radius: the target and anything within 1.5 inches take a Strength 4 hit. Pigeon Roost: resupplied at the start of every game."},
    {"n":"Repeater Handgun","c":50,"d":"","str":"4","rng":24,"ap":-2,"wd":"Move or Fire: may not move and fire. Save Modifier: the -2 armour save penalty. Fire Thrice: up to three shots, extra shots at -1 to hit, each resolved (and targeted) separately. Slow Reload: a full turn of doing nothing to fire more than one shot again. Always uses the optional Blackpowder rules.","rules":["misfire"]},
    {"n":"Repeater Pistol","c":25,"d":"","str":"4","rng":6,"ap":-2,"wd":"Fire Thrice: up to three shots, extra shots at -1 to hit, each resolved (and targeted) separately. Quick Reload: a full shooting phase out of combat and not shooting is needed before firing more than one shot again. Not a Club: after the first round of combat it can no longer be used as a hand weapon. Always uses the optional Blackpowder rules.","rules":["misfire"]},
    {"n":"Fish-hook shot","c":10,"d":"","str":"3","rng":3,"wd":"Thrown Weapon: no range or move penalty. Precise: may target models in combat (but not while the shooter himself is in combat). Caused Fall: may instead try to knock a hit target down with a Strength test (+1 needed against large models)."},
    {"n":"Harpoon crossbow","c":50,"d":"Guides only.","str":"5","rng":30,"wd":"Move or Fire: may not move and fire. Prepare Shot: needs a full turn to prepare before shooting."},
    {"n":"Pebble","c":0,"d":"Free for Snotlings; thrown, range 6 inches.","str":"1","rng":6,"wd":"Free for Snotlings."},
    {"n":"Slingshot","c":2,"d":"Snotlings only; range 18 inches, fires twice at half range.","str":"3","rng":18,"wd":"May fire twice within half range, each at -1 to hit."}
  ]},
  "armour": {"n":"Armour","list":[
    {"n":"Buckler","c":5,"d":""},
    {"n":"Shield","c":5,"svMin":6,"svBonus":1,"d":""},
    {"n":"Helmet","c":10,"d":""},
    {"n":"Light armour","c":20,"sv":6,"d":""},
    {"n":"Heavy armour","c":50,"sv":5,"d":""},
    {"n":"Gromril armour","c":75,"sv":4,"d":"Starting price for Dwarf warbands."},
    {"n":"Enchanted Skins","c":20,"sv":6,"d":"A 6+ special save; 5+ chance to ignore enemy magic."},
    {"n":"Bretonnian Barding","c":30,"d":"Warhorses only."},
    {"n":"Bone Helmet","c":10,"d":""},
    {"n":"Toughened Leathers","c":5,"sv":6,"d":""},
    {"n":"Ithilmar armour","c":60,"sv":5,"d":"Heroes only."},
    {"n":"Barding","c":80,"d":"For the mount."},
    {"n":"Cooking Pot Helmet","c":8,"d":"5+ save against being stunned."},
    {"n":"Mechanical Suit","c":175,"sv":4,"d":"Sorcerer only."},
    {"n":"Cathayan Quilted Silk Armour","c":15,"svBonus":1,"d":"Aristocrat only; +1 to armour saves, combines with other armour."},
    {"n":"Kite Shield","c":10,"svMin":5,"svBonus":2,"d":"5+ on foot; +2 with other armour."}
  ]},
  "misc": {"n":"Miscellaneous equipment","list":[
    {"n":"Holy tome","c":120,"d":""},
    {"n":"Blessed water","c":10,"d":""},
    {"n":"Holy relic","c":15,"d":""},
    {"n":"Hunting arrows","c":35,"d":"Bergjaeger only."},
    {"n":"Squig Prodder","c":15,"d":""},
    {"n":"Mad Cap Mushrooms","c":25,"d":""},
    {"n":"Amulet of the Moon","c":50,"d":""},
    {"n":"Healing Herbs","c":35,"d":""},
    {"n":"Conch Shell Horn","c":25,"d":"Piranha Warrior only."},
    {"n":"Warhorse","c":80,"d":""},
    {"n":"Horse","c":40,"d":""},
    {"n":"Dark Venom","c":15,"d":"Heroes only."},
    {"n":"Sea Dragon Cloak","c":50,"sv":5,"d":"5+ in close combat, 4+ against missiles."},
    {"n":"Magic Gubbinz","c":50,"d":""},
    {"n":"Poisoned Weapon","c":25,"d":""},
    {"n":"Red Toof Tribal Jewellery","c":40,"d":"Frenzy."},
    {"n":"Black Lotus","c":10,"d":"Skink heroes; missile weapons only."},
    {"n":"Reptile Venom","c":5,"d":"Skink henchmen; one battle."},
    {"n":"Hook Hand","c":4,"d":""},
    {"n":"Peg Leg","c":8,"d":""},
    {"n":"Hardtack Biscuits","c":5,"d":""},
    {"n":"Spy Glass","c":20,"d":""},
    {"n":"Compass","c":45,"d":"Plus 2D6 gc."},
    {"n":"Jolly Roger","c":40,"d":"Plus 2D6 gc; heroes only."},
    {"n":"Treasure Map","c":75,"d":"Plus 4D6 gc."},
    {"n":"Parrot","c":15,"d":"Captain and Mates only."},
    {"n":"Ball Shot","c":5,"d":"Swivel Gun ammunition.","str":"5","rng":36,"ap":-2,"wd":"Swivel Gun ammunition. Concussion: an injury roll of 2-4 is Stunned."},
    {"n":"Chain Shot","c":2,"d":"Swivel Gun ammunition.","str":"4","rng":24,"ap":-1,"wd":"Swivel Gun ammunition. A hit that fails to wound knocks the target down on a 4+, even if it normally can't be knocked down."},
    {"n":"Grape Shot","c":2,"d":"Swivel Gun ammunition.","str":"3","rng":24,"wd":"Swivel Gun ammunition. A hit also automatically hits D6 other enemies within 4 inches and in sight (closest first); no armour save modifier; never hits the firer's own warband."},
    {"n":"Forest Cloak","c":50,"d":"Heroes only."},
    {"n":"Elven Cloak","c":75,"d":""},
    {"n":"Standard of Nagarythe","c":75,"d":"Heroes only, at recruitment."},
    {"n":"War Horn of Nagarythe","c":25,"d":"Heroes only."},
    {"n":"Elven Wine","c":50,"d":"Heroes only."},
    {"n":"Elven Runestones","c":50,"d":"Shadow Weavers only."},
    {"n":"Asp Arrows","c":10,"d":"Tomb Lords only; +1 to hit."},
    {"n":"Trip Wire","c":15,"d":""},
    {"n":"Blessed Stag Hide","c":40,"d":""},
    {"n":"Superior Black Powder","c":25,"d":""},
    {"n":"Cathayan silk cloak","c":40,"d":"Emissary only."},
    {"n":"Engine of Chaos","c":125,"d":"Starting price; a captive wagon."},
    {"n":"Lucky Charm","c":10,"d":""},
    {"n":"Crimson shade","c":35,"d":""},
    {"n":"Nightmare","c":95,"d":"Aristocrat only; an undead steed."},
    {"n":"Bird of Prey","c":30,"d":"Aristocrat only."},
    {"n":"Banner of the Noble House","c":25,"d":"+1 Leadership to the bearer."},
    {"n":"Net","c":5,"d":""},
    {"n":"Rope & Hook","c":5,"d":""},
    {"n":"Warhound","c":20,"d":"A trained hound."},
    {"n":"Trap","c":5,"max":5,"d":"One use; Trapmaster only."},
    {"n":"Hooded Lantern & Rig","c":15,"d":"A concealed light; frees the hands."},
    {"n":"Surgeon's Journal","c":80,"d":"Medics only: adjusts a serious injury roll by 1."},
    {"n":"Finger Pendant","c":15,"d":"One-time 5+ save against necromantic magic."},
    {"n":"Lock Picks","c":10,"d":""},
    {"n":"Bearcloak","c":10,"d":"Sheepherders: +1 to armour saves against shooting."},
    {"n":"Staff of Damnation","c":25,"d":"Necrarch only; two-handed, stores a spell."},
    {"n":"Unholy Relic","c":15,"d":""},
    {"n":"Damned Book","c":45,"d":"Enemies within 2 inches are -1 to hit in close combat."},
    {"n":"Sashimono","c":15,"d":"Re-roll non-rout Leadership tests once."},
    {"n":"Horo","c":10,"d":"+1 armour save against missiles when mounted."},
    {"n":"Caltrops","c":15,"d":""},
    {"n":"Flash Powder","c":25,"d":""},
    {"n":"Sharp Stuff","c":3,"d":"Gnoblars only; thrown scrap, first one free."},
    {"n":"Blessed Bolts","c":25,"d":"+1 Strength against chaotic and undead targets."},
    {"n":"Holy Water","c":5,"d":"Heroes only; thrown against the Undead and chaotic."},
    {"n":"Shield of Sigmar","c":20,"d":"A 6+ special save against ranged attacks."},
    {"n":"Pigback Mount","c":50,"d":"Gnoblar heroes only."},
    {"n":"Wolf Rat Mount","c":90,"d":"Clan Moulder only; Movement 9."},
    {"n":"Familiar","c":20,"d":"Plus 2D6 gc; a dog, cat, raven or viper."},
    {"n":"Black Gold Wristbands","c":35,"d":"Plus 2D6 gc; a 6+ save against missiles."},
    {"n":"Ring of Strigos","c":20,"d":"Plus D6 gc; a 6+ save against spells."},
    {"n":"Cursed Book","c":50,"d":"Plus 3D6 gc; enemies within 2 inches are -1 to hit."},
    {"n":"Throat Guard","c":10,"d":"A 6+ save against a Vampire's injury rolls."}
  ]}
};
